config/routes.rb
CurulAdmin::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions" }

  match "initiatives/bulk_update", :to => "bulk_update_initiatives#edit"
  resources :initiatives do
    resource :main, :controller => :main, :only => [:create]
  end

  match "representatives/bulk_update", :to => "bulk_update_representatives#edit"
  resources :representatives do
    resources :comments, only: [] do
      resource :approve, only: :create, controller: 'representatives/comments/approve'
      resource :unapprove, only: :create, controller: 'representatives/comments/unapprove'
    end
  end

  resources :topics
  resources :political_parties
  resources :commissions
  resources :users
  resources :sites
  resources :comments
  
  resources :legislatures do
    resource :actual, controller: 'legislatures/actual', only: :create
  end

  root :to => "dashboard#show"
end

app/models/initiative.rb
# == Schema Information
#
# Table name: initiatives
#
#  id                        :integer          not null, primary key
#  presented_at              :datetime
#  description               :text
#  title                     :text
#  presented_by              :string(255)
#  additional_resources      :text
#  additional_resources_url  :string(255)
#  created_at                :datetime
#  updated_at                :datetime
#  state                     :string(255)
#  official_vote_up          :integer          default(0)
#  official_vote_down        :integer          default(0)
#  representative_id         :integer
#  main                      :boolean
#  political_party_id        :integer
#  voted_at                  :datetime
#  official_vote_abstentions :integer
#  comments_count            :integer          default(0)
#  number                    :string(255)
#  legislature_id            :integer
#  site_id                   :integer
#


class Initiative < ActiveRecord::Base
  #
  # Associations
  #
  has_many :comments, :as => :commentable, :dependent => :destroy
  has_and_belongs_to_many :commissions
  has_many :votes
  has_many :official_votes, :conditions => 'political_party_id NOT IN (8,9)'
  has_many :resources
  has_and_belongs_to_many :commissions
  has_and_belongs_to_many :topics
  belongs_to :representative
  belongs_to :political_party
  belongs_to :legislature

  #
  # Nested Attributes
  #
  attr_accessible :number, :title, :description, :presented_at, :presented_by_token, :commission_tokens, :topic_tokens, :state, :resources_attributes, :official_vote_up, 
        :official_vote_down, :official_vote_abstentions, :official_votes_attributes, :representative_id
  accepts_nested_attributes_for :official_votes
  accepts_nested_attributes_for :resources

  #
  # Attributes
  #
  attr_reader :topic_tokens, :presented_by_token, :commission_tokens

  #
  # Scope
  #
  scope :main, where(:main => true)
  scope :actual_legislature, where(:legislature_id => (Legislature.active ? Legislature.active.id : nil))
  # default_scope {where(site_id: Site.current_id)}

  #
  # Pagination
  #
  # paginates_per 5
  
  #
  # Extensions
  #
  include SolrSearch::InitiativesSearch

  #
  # States
  #
  STATES = {
    :new => 'nueva',
    :presentation => 'presentacion',
    :commission => 'en comision',
    :plenary => 'en pleno',
    :project => 'proyecto',
    :rejected_by_commission => 'desechada en comision',
    :rejected_by_board => 'desechada por la mesa directiva'
  }

  #
  # Delegates
  #
  delegate :name, to: :representative, prefix: true, allow_nil: true

  #
  # States Machine
  #
  state_machine :state, :initial => :new do
    state :new
    state :presentation
    state :commission
    state :plenary
    state :project
    state :rejected_by_commission
    state :rejected_by_board

    event :in_presentation do
      transition :to => :presentation, :from => :any
    end

    event :in_commission do
      transition :to => :commission, :from => :any
    end

    event :in_plenary do
      transition :to => :plenary, :from => :any
    end

    event :in_project do
      transition :to => :project, :from => :any
    end
  end

  def topic_tokens=(ids)
    self.topic_ids = ids.split(',')
  end

  def presented_by_token=(id)
    self.representative_id = id
  end

  def commission_tokens=(ids)
    self.commission_ids = ids.split(',')
  end

  def official_percentage_up
    p1 = (((official_vote_up.to_f*100)/total_official_votes))
    p1.nan? ? 0 : p1.round
  end

  def official_percentage_down
    p1 = ((official_vote_down.to_f*100)/total_official_votes)
    p1.nan? ? 0 : p1.round
  end

  def official_pixel_votes_up
    ((official_percentage_up.to_f/100)*383).to_i
  end

  def official_pixel_votes_down
    ((official_percentage_down.to_f/100)*383).to_i
  end

  def total_official_votes
    official_vote_up + official_vote_down
  end

  def official_voted?
    official_vote_up > 0 && official_vote_down > 0
  end

  def percentage_votes_up
    if votes_up > 0
      ((votes_up.to_f*100)/total_votes).round
    else
      0
    end
  end

  def percentage_votes_down
    if votes_down > 0
      ((votes_down.to_f*100)/total_votes).round
    else
      0
    end
  end

  def pixel_votes_up
    if votes_up > 0
      ((percentage_votes_up.to_f/100)*383).to_i
    else
      0
    end
  end

  def pixel_votes_down
    if votes_down > 0
      ((percentage_votes_down.to_f/100)*383).to_i
    else
      0
    end
  end

  def total_votes
    votes.count
  end

  def votes_up
    votes.votes_up.count
  end

  def votes_down
    votes.votes_down.count
  end

  def voted?
    votes_up > 0 || votes_down > 0
  end

  def state_formated
    STATES[state.to_sym]
  end

  def self.to_home
    initiative =  self.order('RANDOM()').limit(5)
    return self.main.first ? [self.main.first, initiative.first] : [initiative.first, initiative.last]
  end

  def presented?
    self.state != 'new'
  end

  def commissioned?
    self.state == 'commission' || self.state == 'plenary' || self.state == 'project' || self.state == 'rejected_by_commission'
  end

  def plenaried?
    self.state == 'plenary' || self.state == 'project'
  end

  def projected?
    self.state == 'project'
  end

  def official_votes_objects(create = false)
    if official_votes.empty?
      PoliticalParty.all.each do |political_party|
        official_vote = official_votes.build :political_party => political_party
        official_vote.save if create
      end
    end
  end
end

app/controllers/initiatives_controller.rb
class InitiativesController < ApplicationController
  load_and_authorize_resource
  
  def index
    @initiatives = if params[:search]
            Initiative.filters(params[:search]).results
          else
            Initiative.page(params[:page])
          end
  end

  def show
    @initiative = Initiative.find(params[:id])
    respond_to do |format|
      format.html
      format.json { render :json => @initiative.attributes }
    end
  end

  def new
    @initiative = Initiative.new
    @initiative.official_votes_objects
    @initiative.resources.build
  end

  def create
    @initiative = Initiative.new(params[:initiative])
    if @initiative.save
      redirect_to initiatives_url, :notice => "Iniciativa creada exitosamente"
    else
      render :new
    end
  end

  def update
    @initiative = Initiative.find(params[:id])
    if @initiative.update_attributes(params[:initiative])
      respond_to do |format|
        format.html { redirect_to(initiatives_url, :notice => "Iniciativa editada exitosamente") }
        format.json { render json: @initiative}
      end
    else
      render :edit
    end
  end

  def edit
    @initiative = Initiative.find(params[:id])
    @initiative.official_votes_objects true
    @initiative.resources.build
  end

  def destroy
    @initiative = Initiative.find(params[:id])
    @initiative.destroy
    redirect_to initiatives_url
  end
end

app/helpers/initiatives_helper.rb
module InitiativesHelper
end

app/views/initiatives/_form.html.haml
%fieldeset
  %legend Iniciativa
  .control-group
    = form.label :id, class: 'control-label'
    .controls
      = form.text_field :id, :class => 'xxlarge', :disabled => :disabled

  .control-group
    = form.label :numero, class: 'control-label'
    .controls
      = form.text_field :number, :class => 'xxlarge'

  .control-group
    = form.label :titulo, class: 'control-label'
    .controls
      = form.text_field :title, :class => 'xxlarge'

  .control-group
    = form.label :descripcion, class: 'control-label'
    .controls
      = form.text_area :description, :class => 'tinymce'

  .control-group
    = form.label :fecha, class: 'control-label'
    .controls
      #presented_at.input-append.date{'data-date' => "#{@initiative.try(:presented_at) || Time.now.strftime('%Y-%m-%d')}", 'data-date-format' => 'yyyy-mm-dd'}
        = form.text_field :presented_at
        %span.add-on
          %i.icon-calendar

  .control-group
    = form.label :promovente, class: 'control-label'
    .controls
      = form.text_field :presented_by_token, "data-pre" => @initiative.representative.to_json(methods: :name)

  .control-group
    = form.label :comisiones, class: 'control-label'
    .controls
      = form.text_field :commission_tokens, "data-pre" => @initiative.commissions.to_json

  .control-group
    = form.label :temas, class: 'control-label'
    .controls
      = form.text_field :topic_tokens, "data-pre" => @initiative.topics.map(&:attributes).to_json

  .control-group
    = form.label :estado, class: 'control-label'
    .controls
      = form.select :state, Initiative::STATES.to_a.each {|t| t.reverse!}

%fieldeset
  %legend Recursos Adicionales
  
  = form.fields_for :resources do |resource_form|
    .control-group
      = resource_form.label :nombre, class: 'control-label'
      .controls
        = resource_form.text_field :name, :class => 'xxlarge'

    .control-group
      = resource_form.label :url, class: 'control-label'
      .controls
        = resource_form.text_field :url, :class => 'xxlarge'

%fieldeset
  %legend Votaciones

  .control-group
    = form.label :a_favor, class: 'control-label'
    .controls
      = form.text_field :official_vote_up, :class => 'xxlarge'

  .control-group
    = form.label :en_contra, class: 'control-label'
    .controls
      = form.text_field :official_vote_down, :class => 'xxlarge'

  .control-group
    = form.label :abstenciones, class: 'control-label'
    .controls
      = form.text_field :official_vote_abstentions, :class => 'xxlarge'

  = form.fields_for :official_votes do |official_vote_form|
    .control-group
      %label.control-label
        = image_tag(official_vote_form.object.political_party.logo.url(:thumb))
      .controls
        = official_vote_form.text_field :votes, :class => 'xxlarge'
        = official_vote_form.hidden_field :political_party_id

- content_for :javascript do
  $('#presented_at').datepicker();

app/views/initiatives/_initiative.html.haml
%tr
  %td= initiative.id
  %td= initiative.title
  %td= initiative.representative.try(:name)
  %td= initiative.presented_at.to_date.to_s(:long)
  %td
    = link_to 'Edicion rapida', '#', class: 'btn btn-primary btn-mini quick-edition', 'data-initiative-id' => initiative.id
    = link_to 'Editar', edit_initiative_path(initiative), class: 'btn btn-primary btn-mini'
    = (initiative.main)? 'Principal' : link_to('Principal', initiative_main_path(initiative), :method => :post, class: 'btn btn-primary btn-mini')
    = link_to 'Borrar', initiative_path(initiative), :method => :delete, :confirm => '¿Esta seguro que desea eliminar la iniciativa?', class: 'btn btn-danger btn-mini'

app/views/initiatives/edit.html.haml
.box
  .box-title
    %h2 Editar Iniciativa ##{@initiative.number}
  
  .box-content
    = form_for @initiative, :html => {:multipart => true, class: 'form-horizontal'} do |form|
      = render "shared/error_messages", :target => @initiative
      %fieldset
        = render :partial => 'form', :locals => {:form => form}
        .actions
          = form.submit 'Actualizar Iniciativa', :class => 'btn primary'
          %input{:type => 'reset', :class => 'btn', :value => 'Limpiar'}

app/views/initiatives/index.html.haml
.box
  .box-title
    %h2 Iniciativas

  .box-content
    = form_tag initiatives_path, :method => :get do
      .row-fluid
        .span4
          = label_tag :titulo
          .input
            = text_field_tag 'search[title]'
        .span4
          = label_tag :description
          .input
            = text_field_tag 'search[description]'
        .span4
          = label_tag :status
          .input
            = select_tag 'search[state]', options_for_select(Initiative::STATES.map( &:reverse)), {:include_blank => true}
      .row-fluid
        .span4
          = label_tag :comision
          .input
            = text_field_tag 'search[commission_ids]'
        .span4
          = label_tag :presentado_por
          .input
            = text_field_tag 'search[representative_name]'

      .row-fluid
        .span4
          = submit_tag 'Buscar', :class => [:btn, :primary]
    
    #datatable_wrapper.dataTables_wrapper{role: 'grid'}
      #datatable_length.dataTables_length
        = link_to 'Nueva Iniciativa', new_initiative_path  , :class => [:btn, 'btn-primary']
        
        = link_to 'Bulk Update', initiatives_bulk_update_path  , :class => [:btn, 'btn-primary']

      %table.table.table-striped.table-bordered.dataTable
        %thead
          %tr
            %th #
            %th Titulo
            %th Presentado por
            %th Presentado el
            %th

        %tbody
          = render @initiatives

        %tfoot
          %tr
            %th #
            %th Titulo
            %th Presentado por
            %th Presentado el
            %th
      #datatable_paginate.dataTables_paginate.paging_full_numbers
        = paginate @initiatives

#quick-edition-modal.modal.hide.fade
  .modal-header
    %button{type: "button", class: "close", 'data-dismiss' => "modal", 'aria-hidden' => "true"} &times;
    %h3 Edicion rapida
  .modal-body
    = form_tag '', method: :put, class: 'form-horizontal' do
      .control-group
        = label_tag 'initiative[title]', 'Titulo', class: 'control-label'
        .controls
          = text_field_tag 'initiative[title]'

      .control-group
        = label_tag 'initiative[description]', 'Descripcion', class: 'control-label'
        .controls
          = text_area_tag 'initiative[description]', '', class: 'tinymce'

      .control-group
        = label_tag 'initiative[state]', 'Estado', class: 'control-label'
        .controls
          = select_tag 'initiative[state]', options_for_select(Initiative::STATES.to_a.each {|t| t.reverse!})

  .modal-footer
    %a#close-modal.btn{href: "#"} Cerrar
    %a#quick-edition-submit.btn.btn-primary{href: "#"} Guardar cambios

- content_for :javascript do
  $('.quick-edition').click(function(event){
  event.preventDefault();
  form = $('#quick-edition-modal form');
  $.getJSON('initiatives/' + $(this).data('initiative-id') +'.json', function(data){
  form.attr('action','/admin/initiatives/' + data.id)
  form.find('#initiative_title').val(data.title);
  tinyMCE.get('initiative_description').setContent(data.description)
  form.find('select option[value=' + data.state + ']').attr('selected','selected');
  });

  $('#quick-edition-modal').modal();
  });

  $('#quick-edition-modal').on('hide', function() {
  form = $('#quick-edition-modal form');
  form.find('input').val('');
  form.find('option:selected').removeAttr('selected');
  });
  
  $('#close-modal').click(function(event){
  event.preventDefault();
  $('#quick-edition-modal').modal('hide');
  });
  
  $('#quick-edition-submit').click(function(event) {
  event.preventDefault();
  $('#quick-edition-modal form').submit();
  });

app/views/initiatives/new.html.haml
.box
  .box-title
    %h2 Nueva Iniciativa
  
  .box-content
    = form_for @initiative, :html => {:multipart => true, class: 'form-horizontal'} do |form|
      = render "shared/error_messages", :target => @initiative
      %fieldset
        = render :partial => 'form', :locals => {:form => form}
        .actions
          = form.submit 'Crear Iniciativa', :class => 'btn primary'
          %input{:type => 'reset', :class => 'btn', :value => 'Limpiar'}