config/routes.rb
CurulAdmin::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions" }

  match "initiatives/bulk_update", :to => "bulk_update_initiatives#edit"
  resources :initiatives do
    resource :main, :controller => :main, :only => [:create]
  end

  match "representatives/bulk_update", :to => "bulk_update_representatives#edit"
  resources :representatives do
    resources :comments, only: [] do
      resource :approve, only: :create, controller: 'representatives/comments/approve'
      resource :unapprove, only: :create, controller: 'representatives/comments/unapprove'
    end
  end

  resources :topics
  resources :political_parties
  resources :commissions
  resources :users
  resources :sites
  resources :comments
  
  resources :legislatures do
    resource :actual, controller: 'legislatures/actual', only: :create
  end

  root :to => "dashboard#show"
end

app/models/political_party.rb
# == Schema Information
#
# Table name: political_parties
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  logo       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  site_id    :integer
#

class PoliticalParty < ActiveRecord::Base

  #
  # Accessors
  #
  attr_accessible :name, :logo, :logo_cache

  #
  # Associations
  #
  has_many :representatives

  #
  # Uploader
  #
  mount_uploader :logo, LogoUploader

  #
  # Scope
  #
  scope :political_parties, where('id NOT IN (8,9)')
  default_scope {where(site_id: Site.current_id)}

  def initials
    name.split(' ').collect {|word| word.first.downcase}.join('')
  end
end

app/controllers/political_parties_controller.rb
class PoliticalPartiesController < ApplicationController
  load_and_authorize_resource
  
  def index
    @political_parties = PoliticalParty.page(params[:page])
  end
  
  def show
    @political_party = PoliticalParty.find(params[:id])
  end
  
  def new
    @political_party = PoliticalParty.new
  end
  
  def create
    @political_party = PoliticalParty.new(params[:political_party])
    if @political_party.save
      redirect_to political_parties_url, :notice => "Etapa creada exitosamente"
    else
      render :new
    end
  end
  
  def update
    @political_party = PoliticalParty.find(params[:id])
    if @political_party.update_attributes(params[:political_party])
      redirect_to political_parties_url, :notice => "Etapa editada exitosamente"
    else
      render :edit
    end
  end
  
  def edit
    @political_party = PoliticalParty.find(params[:id])
  end
  
  def destroy
    @political_party = PoliticalParty.find(params[:id])
    @political_party.destroy
    redirect_to political_parties_url
  end
  
end

app/helpers/political_parties_helper.rb
module PoliticalPartiesHelper
end

app/views/political_parties/_form.html.haml
.contro-group
  = form.label :nombre, class: 'control-label'
  .controls
    = form.text_field :name, :class => 'xxlarge'

.contro-group
  = form.label :logotipo, class: 'control-label'
  .controls
    = form.file_field :logo, :class => 'xxlarge'
    = form.hidden_field :logo_cache

app/views/political_parties/_political_party.html.haml
%tr
  %td= political_party.name
  %td.center= image_tag political_party.logo.url(:thumb)
  %td
    = link_to 'Editar', edit_political_party_path(political_party), class: 'btn btn-primary btn-mini'
    = link_to 'Borrar', political_party_path(political_party), :method => :delete, :confirm => '¿Esta seguro que desea eliminar la iniciativa?', class: 'btn btn-danger btn-mini'

app/views/political_parties/edit.html.haml
.box
  .box-title
    %h2 Editar Partido Politico

  .box-content
    = form_for @political_party, :html => {:multipart => true, class: 'form-horizontal'} do |form|
      = render "shared/error_messages", :target => @political_party
      %fieldset
        = render :partial => 'form', :locals => {:form => form}
        .form-actions
          = form.submit 'Editar Partido Politico', :class => 'btn btn-primary'
          %input{:type => 'reset', :class => 'btn', :value => 'Limpiar'}

app/views/political_parties/index.html.haml
.box
  .box-title
    %h2 Partidos Politicos

  .box-content
    #datatable_wrapper.dataTables_wrapper{role: 'grid'}
      #datatable_length.dataTables_length
        = link_to 'Nuevo Partido Politico', new_political_party_path  , :class => [:btn, 'btn-primary']

        %table.table.table-striped.table-bordered.dataTable
          %thead
            %tr
              %th Nombre
              %th Logotipo
              %th

          %tbody
            = render @political_parties

          %tfoot
            %tr
              %th Nombre
              %th Logotipo
              %th


      #datatable_paginate.dataTables_paginate.paging_full_numbers
        = paginate @political_parties

app/views/political_parties/new.html.haml
.box
  .box-title
    %h2 Nuevo Partido Politico

  .box-content
    = form_for @political_party, :html => {:multipart => true, class: 'form-horizontal'} do |form|
      = render "shared/error_messages", :target => @political_party
      %fieldset
        = render :partial => 'form', :locals => {:form => form}
        .form-actions
          = form.submit 'Crear Partido Politico', :class => 'btn btn-primary'
          %input{:type => 'reset', :class => 'btn', :value => 'Limpiar'}