config/routes.rb
CurulAdmin::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions" }

  match "initiatives/bulk_update", :to => "bulk_update_initiatives#edit"
  resources :initiatives do
    resource :main, :controller => :main, :only => [:create]
  end

  match "representatives/bulk_update", :to => "bulk_update_representatives#edit"
  resources :representatives do
    resources :comments, only: [] do
      resource :approve, only: :create, controller: 'representatives/comments/approve'
      resource :unapprove, only: :create, controller: 'representatives/comments/unapprove'
    end
  end

  resources :topics
  resources :political_parties
  resources :commissions
  resources :users
  resources :sites
  resources :comments
  
  resources :legislatures do
    resource :actual, controller: 'legislatures/actual', only: :create
  end

  root :to => "dashboard#show"
end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  site_id    :integer
#

class Topic < ActiveRecord::Base

  #
  # Accessors
  #
  attr_accessible :name

  #
  # Associations
  #
  has_and_belongs_to_many :initiatives

  #
  # Validations
  #
  validates :name, :presence => true, :uniqueness => true

  #
  # Scopes
  #
  default_scope :order => 'name ASC'
  default_scope {where(site_id: Site.current_id)}
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  load_and_authorize_resource
  def index
    @topics = if params[:q]
      Topic.where("name like ?", "%#{params[:q]}%")
    else
      if params[:search]
        Topic.where("topics.name @@ ?", params[:search][:name]).page(params[:page])
      else
        Topic.page(params[:page])
      end
    end
    respond_to do |format|
      format.html
      format.json { render :json => @topics.map(&:attributes) }
    end
  end
  
  def show
    @topic = Topic.find(params[:id])
  end
  
  def new
    @topic = Topic.new
  end
  
  def create
    @topic = Topic.new(params[:topic])
    if @topic.save
      redirect_to topics_url, :notice => "Tema creado exitosamente"
    else
      render :new
    end
  end
  
  def update
    @topic = Topic.find(params[:id])
    if @topic.update_attributes(params[:topic])
      redirect_to topics_url, :notice => "Tema editado exitosamente"
    else
      render :edit
    end
  end
  
  def edit
    @topic = Topic.find(params[:id])
  end
  
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy
    redirect_to topics_url
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.haml
.control-group
  = form.label :nombre, class: 'control-label'
  .controls
    = form.text_field :name, :class => 'xxlarge'

app/views/topics/_topic.html.haml
%tr
  %td= topic.name
  %td
    = link_to 'Editar', edit_topic_path(topic), class: 'btn btn-primary btn-mini'
    = link_to 'Borrar', topic_path(topic), :method => :delete, :confirm => '¿Esta seguro que desea eliminar el tema?', class: 'btn btn-danger btn-mini'

app/views/topics/edit.html.haml
.box
  .box-title
    %h2 Editar Tema

  .box-content  
    = form_for @topic, :html => {:multipart => true} do |form|
      = render "shared/error_messages", :target => @topic
      %fieldset
        = render :partial => 'form', :locals => {:form => form}
        .form-actions
          = form.submit 'Editar Tema', :class => 'btn btn-primary'
          %input{:type => 'reset', :class => 'btn', :value => 'Limpiar'}

app/views/topics/index.html.haml
.box
  .box-title
    %h2 Temas

  .box-content
    = form_tag topics_path, :method => :get do
      .row-fluid
        .span4
          = label_tag :tema
          .input
            = text_field_tag 'search[name]'
            
      .row-fluid
        .span4
          = submit_tag 'Buscar', :class => [:btn, :primary]
  

    #datatable_wrapper.dataTables_wrapper{role: 'grid'}
      #datatable_length.dataTables_length
        = link_to 'Nuevo Tema', new_topic_path, :class => [:btn, 'btn-primary']

      %table.table.table-striped.table-bordered.dataTable
        %thead
          %tr
            %th Tema
            %th Acciones

        %tbody
          = render @topics

        %tfoot
          %tr
            %th Tema
            %th Acciones

    #datatable_paginate.dataTables_paginate.paging_full_numbers
      = paginate @topics

app/views/topics/new.html.haml
.box
  .box-title
    %h2 Nuevo Tema

  .box-content  
    = form_for @topic, :html => {:multipart => true, class: 'form-horizontal'} do |form|
      = render "shared/error_messages", :target => @topic
      %fieldset
        = render :partial => 'form', :locals => {:form => form}
        .form-actions
          = form.submit 'Crear Tema', :class => 'btn btn-primary'
          %input{:type => 'reset', :class => 'btn', :value => 'Limpiar'}