config/routes.rb
CurulAdmin::Application.routes.draw do
  devise_for :users, :controllers => { :sessions => "sessions" }

  match "initiatives/bulk_update", :to => "bulk_update_initiatives#edit"
  resources :initiatives do
    resource :main, :controller => :main, :only => [:create]
  end

  match "representatives/bulk_update", :to => "bulk_update_representatives#edit"
  resources :representatives do
    resources :comments, only: [] do
      resource :approve, only: :create, controller: 'representatives/comments/approve'
      resource :unapprove, only: :create, controller: 'representatives/comments/unapprove'
    end
  end

  resources :topics
  resources :political_parties
  resources :commissions
  resources :users
  resources :sites
  resources :comments
  
  resources :legislatures do
    resource :actual, controller: 'legislatures/actual', only: :create
  end

  root :to => "dashboard#show"
end

app/models/representative.rb
# encoding: utf-8
# == Schema Information
#
# Table name: representatives
#
#  id                 :integer          not null, primary key
#  position           :string(255)
#  region_id          :integer
#  province_id        :integer
#  avatar             :string(255)
#  biography          :text
#  birthday           :string(255)
#  twitter            :string(255)
#  facebook           :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  political_party_id :integer
#  district           :string(255)
#  phone              :string(255)
#  email              :string(255)
#  substitute         :string(255)
#  election_type      :string(255)
#  old_commissions    :string(255)
#  comments_count     :integer          default(0)
#  circumscription    :string(255)
#  legislature_id     :integer
#  sex                :string(255)
#  first_name         :string(255)
#  last_name          :string(255)
#  site_id            :integer
#

class Representative < ActiveRecord::Base

  #
  # Associatons
  #
  belongs_to :region
  belongs_to :province
  belongs_to :political_party
  belongs_to :legislature
  has_and_belongs_to_many :commissions
  has_many :initiatives
  has_many :comments, :as => :commentable, :dependent => :destroy

  #
  # Accessor
  #
  attr_reader :commission_tokens
  attr_accessible :first_name, :last_name, :region_id, :avatar, :avatar_cache, :biography, :birthday, :sex, :email, :phone, :twitter, :facebook, 
        :political_party_id, :substitute, :election_type, :commission_tokens, :position, :district, :circumscription

  #
  # Uploader
  #
  mount_uploader :avatar, AvatarUploader

  #
  # scopes
  #
  scope :by_region, lambda {|region_id| where(:region_id => region_id)}
  scope :by_commission, lambda {|commission_id| joins(:commissions).where('commissions_representatives.commission_id = ?', commission_id)}
  scope :most_commented, order('comments_count DESC')
  scope :political_parties, where('political_party_id NOT IN (8,9)')
  scope :actual_legislature, where(:legislature_id => (Legislature.active ? Legislature.active.id : nil))
  # default_scope {where(site_id: Site.current_id)}

  #
  # Delegates
  #
  delegate :name, to: :region, prefix: true, allow_nil: true
  delegate :name, to: :political_party, prefix: true, allow_nil: true
  
  #
  # Constants
  #
  ELECTION_TYPE = [['Mayoría Relativa','Mayoría Relativa'],['Representación proporcional','Representación proporcional']]
  POSITION = [['Diputado','Diputado'],['Senado','Senado'],['Ejecutivo','Ejecutivo']]
  
  #
  # Extensions
  #
  include SolrSearch::RepresentativesSearch
  
  
  def name
    "#{first_name} #{last_name}"
  end

  def commission_tokens=(ids)
    self.commission_ids = ids.split(',')
  end

  def photo(size = nil)
    return self.avatar.url(size) unless self.avatar.url.nil? || self.avatar.url.include?('txt')
    unless size
      'front/missing.png'
    else
      'front/thumb_missing.png'
    end
  end

  # def as_json(options)
  #   options.merge!({include: [:region, :political_party], methods: [:photo]}) if options
  #   super(options)
  # end
  
  def to_json_for_bulk_update
    #.map {||}
  end
end

app/controllers/representatives/comments/approve_controller.rb
class ::Representatives::Comments::ApproveController < ApplicationController
  def create
    @representative = Representative.find params[:representative_id]
    @comment = @representative.comments.find params[:comment_id]
    @comment.approve!
    redirect_to representative_url(@representative)
  end
end

app/controllers/representatives/comments/unapprove_controller.rb
class ::Representatives::Comments::UnapproveController < ApplicationController
  
  def create
    @representative = Representative.find params[:representative_id]
    @comment = @representative.comments.find params[:comment_id]
    @comment.unapprove!
    redirect_to representative_url(@representative)
  end
end

app/controllers/representatives_controller.rb
class RepresentativesController < ApplicationController
  load_and_authorize_resource
  
  def index
    @representatives =   if params[:q]
        Representative.where("name ilike ?", "%#{params[:q]}%")
      else
        if params[:search]
          Representative.filters(params[:search]).results
        else
          Representative.page(params[:page])
        end
      end
    respond_to do |format|
      format.html
      format.json { render :json => @representatives.map(&:attributes) }
    end
  end
  
  def show
    @representative = Representative.find(params[:id])
    @comments = @representative.comments.page(params[:page]).per(5).order('created_at DESC')
    respond_to do |format|
      format.html
      format.json { render :json => @representative }
    end
  end

  def new
    @representative = Representative.new
    @regions = Region.all.collect {|state| [state.name, state.id]}
    @provinces = []
    @political_parties = PoliticalParty.all.collect {|political_party| [political_party.name, political_party.id]}
  end

  def create
    @representative = Representative.new(params[:representative])
    if @representative.save
      redirect_to representatives_url, :notice => "Representante creado exitosamente"
    else
      render :new
    end
  end

  def edit
    @representative = Representative.find(params[:id])
    @regions = Region.all.collect {|state| [state.name, state.id]}
    @provinces = []
    @political_parties = PoliticalParty.all.collect {|political_party| [political_party.name, political_party.id]}
  end

  def update
    @representative = Representative.find(params[:id])
    if @representative.update_attributes(params[:representative])
      respond_to do |format|
        format.html { redirect_to(representatives_url, :notice => "Representante editado exitosamente") }
        format.json { render json: @representative}
      end
    else
      render :edit
    end
  end

  def destroy
    @representative = Representative.find(params[:id])
    @representative.destroy
    redirect_to representatives_url, :notice => "Representante eliminado exitosamente"
  end
end

app/helpers/representatives_helper.rb
module RepresentativesHelper
  
  def comment_action_link_name(comment)
    comment.approved ? 'Desaprovar' : 'Aprovar'
  end
  
  def comment_action_link_url(comment)
    comment.approved ? admin_representative_comment_unapprove_path(comment.commentable, comment) : admin_representative_comment_approve_path(comment.commentable, comment)
  end
  
  def comment_action_link_class(comment)
    comment.approved ? 'btn-danger' : 'btn-primary'
  end
end

app/views/representatives/_comment.html.haml
%tr
  %td= comment.comment
  %td= comment.author
  %td
    = link_to comment_action_link_name(comment), comment_action_link_url(comment), method: :post, class: [:btn, comment_action_link_class(comment)]

app/views/representatives/_form.html.haml
%fieldeset
  %legend Informacion personal
  .control-group
    = form.label :nombres, class: 'control-label'
    .controls
      = form.text_field :first_name, :class => 'xxlarge'

  .control-group
    = form.label :apellidos, class: 'control-label'
    .controls
      = form.text_field :last_name, :class => 'xxlarge'

    
  .control-group
    = form.label :region, class: 'control-label'
    .controls
      = form.select :region_id, @regions, { :include_blank => true }
    
  / .control-group
  /   = form.label :provincia, class: 'control-label'
  /   .controls
  /     = form.select :province_id, @provinces, { :include_blank => true}

  .control-group
    = form.label :avatar, class: 'control-label'
    .controls
      = form.file_field :avatar, :class => 'xxlarge'
      = form.hidden_field :avatar_cache
    
  .control-group
    = form.label :biografia, class: 'control-label'
    .controls
      = form.text_area :biography, :class => 'tinymce'
    
  .control-group
    = form.label :fecha_de_nacimiento, class: 'control-label'
    .controls
      #birthday.input-append.date{'data-date' => "#{@representative.try(:birthday) || Time.now.strftime('%Y-%m-%d')}", 'data-date-format' => 'yyyy-mm-dd'}
        = form.text_field :birthday
        %span.add-on
          %i.icon-calendar

  .control-group
    = form.label :genero, class: 'control-label'
    .controls
      = form.select :sex, [['Femenino','f'],['Masculino','m']], { :include_blank => true}

%fieldeset
  %legend Informacion de contacto
  
  .control-group
    = form.label :email, class: 'control-label'
    .controls
      = form.text_field :email, :class => 'xxlarge'

  .control-group
    = form.label :telefono, class: 'control-label'
    .controls
      = form.text_field :phone, :class => 'xxlarge'

  .control-group
    = form.label :twitter, class: 'control-label'
    .controls
      = form.text_field :twitter, :class => 'xxlarge'

  .control-group
    = form.label :facebook, class: 'control-label'
    .controls
      = form.text_field :facebook, :class => 'xxlarge'

%fieldeset
  %legend Informacion politica
  
  .control-group
    = form.label :partido_politico, class: 'control-label'
    .controls
      = form.select :political_party_id, @political_parties, { :include_blank => true}

  .control-group
    = form.label :substituto, class: 'control-label'
    .controls
      = form.text_field :substitute, :class => 'xxlarge'

  .control-group
    = form.label :tipo_de_eleccion, class: 'control-label'
    .controls
      = form.select :election_type, options_for_select(Representative::ELECTION_TYPE, selected: @representative.election_type), {:include_blank => true}

  .control-group
    = form.label :comisiones, class: 'control-label'
    .controls
      = form.text_field :commission_tokens, "data-pre" => @representative.commissions.map(&:attributes).to_json

  .control-group
    = form.label :posicion, class: 'control-label'
    .controls
      = form.select :position, options_for_select(Representative::POSITION, selected: @representative.position)
    
  .control-group
    = form.label :distrito, class: 'control-label'
    .controls
      = form.text_field :district, :class => 'xxlarge'

  .control-group
    = form.label :circunscripcion, class: 'control-label'
    .controls
      = form.text_field :circumscription, :class => 'xxlarge'
      
- content_for :javascript do
  $('#birthday').datepicker();

app/views/representatives/_representative.html.haml
%tr
  %td= link_to representative.name, representative_path(representative) if representative
  %td= representative.political_party_name if representative
  %td= representative.region_name if representative
  %td
    = link_to 'Edicion rapida', '#', class: 'btn btn-primary btn-mini quick-edition', 'data-representative-id' => representative.id
    = link_to 'Editar', edit_representative_path(representative), class: 'btn btn-primary btn-mini'
    = link_to 'Borrar', representative_path(representative), :method => :delete, :confirm => '¿Esta seguro que desea eliminar la iniciativa?', class: 'btn btn-danger btn-mini'

app/views/representatives/bulk.html.haml
.page-header
  %h2 Bulk Update

.well.row
  = form_tag '/admin/representatives/bulk', :method => :get do
    .span16.bottom-margin-20
      .span7
        = label_tag :nombre
        .input
          = text_field_tag 'search[name]'
      .span7
        = label_tag :estado
        .input
          = select_tag 'search[state]', options_from_collection_for_select(Region.all,'id','name'), {:include_blank => true}
    .span16.bottom-margin-20
      .span7
        = label_tag :partido_politico
        .input
          = select_tag 'search[political_party]', options_from_collection_for_select(PoliticalParty.all,'id','name'), {:include_blank => true}
      .span7
        = label_tag :comision
        .input
          = text_field_tag 'search[commision]'

    .span16.bottom-margin-20
      .span7
        = submit_tag 'Buscar', :class => [:btn, :primary]


= form_tag '/admin/representatives/bulk_update' do
  = submit_tag 'Actualizar', :class => [:btn, :primary]
  %table.zebra-striped
    %thead
      %tr
        %th Nombre
        %th Distrito
        %th Circunscripcion
        %th Email
        %th Telefono
        %th Biografia
        %th Twitter

    %tbody
      - @representatives.each do |representative|
        %tr
          %td= text_field_tag 'representatives[][name]', representative.name
          %td= text_field_tag 'representatives[][district]', representative.district
          %td= text_field_tag 'representatives[][circumscription]', representative.circumscription
          %td= text_field_tag 'representatives[][email]', representative.email
          %td= select_tag 'representatives[][political_party]', options_from_collection_for_select(PoliticalParty.all,'id','name', representative.political_party_id)
          %td= select_tag 'representatives[][region]', options_from_collection_for_select(Region.all,'id','name', representative.region_id)
          %td= text_field_tag 'representatives[][twitter]', representative.twitter
        = hidden_field_tag 'representatives[][id]', representative.id
  = submit_tag 'Actualizar', :class => [:btn, :primary]

app/views/representatives/edit.html.haml
.box
  .box-title
    %h2 Editar Representante

  .box-content  
    = form_for @representative, :html => {:multipart => true, class: 'form-horizontal'} do |form|
      = render "shared/error_messages", :target => @representative
      = render :partial => 'form', :locals => {:form => form}
      .form-actions
        = form.submit 'Editar Representante', :class => 'btn btn-primary'
        %input{:type => 'reset', :class => 'btn', :value => 'Limpiar'}

app/views/representatives/index.html.haml
.box
  .box-title
    %h2 Representantes

  .box-content
    = form_tag representatives_path, :method => :get do
      .row-fluid
        .span4
          = label_tag :nombre
          .input
            = text_field_tag 'search[name]'
        .span4
          = label_tag :estado
          .input
            = select_tag 'search[region_name]', options_from_collection_for_select(Region.all,'id','name'), {:include_blank => true}
        .span4
          = label_tag :partido_politico
          .input
            = select_tag 'search[political_party_name]', options_from_collection_for_select(PoliticalParty.all,'id','name'), {:include_blank => true}
      .row-fluid
        .span4
          = label_tag :comision
          .input
            = text_field_tag 'search[commission_ids]'
        .span4
          = label_tag :email
          .input
            = text_field_tag 'search[email]'
        .span4
          = label_tag :twitter
          .input
            = text_field_tag 'search[twitter]'

      .row-fluid
        .span4
          = submit_tag 'Buscar', :class => [:btn, :primary]
    #datatable_wrapper.dataTables_wrapper{role: 'grid'}
      #datatable_length.dataTables_length
        = link_to 'Nuevo Representante', new_representative_path  , :class => [:btn, 'btn-primary']

        = link_to 'Bulk Update', representatives_bulk_update_path  , :class => [:btn, 'btn-primary']

      %table.table.table-striped.table-bordered.dataTable
        %thead
          %tr
            %th Nombre
            %th Partido politico
            %th Estado
            %th Acciones

        %tbody
          = render @representatives
          
        %tfoot
          %tr
            %th Nombre
            %th Partido politico
            %th Estado
            %th Acciones

      #datatable_paginate.dataTables_paginate.paging_full_numbers
        = paginate @representatives

#quick-edition-modal.modal.hide.fade
  .modal-header
    %button{type: "button", class: "close", 'data-dismiss' => "modal", 'aria-hidden' => "true"} &times;
    %h3 Edicion rapida
  .modal-body
    = form_tag '', method: :put, class: 'form-horizontal' do
      .control-group
        = label_tag 'representative[first_name]', 'Nombre', class: 'control-label'
        .controls
          = text_field_tag 'representative[first_name]'

      .control-group
        = label_tag 'representative[last_name]', 'Nombre', class: 'control-label'
        .controls
          = text_field_tag 'representative[last_name]'


      .control-group
        = label_tag 'representative[district]', 'Distrito', class: 'control-label'
        .controls
          = text_field_tag 'representative[district]'

      .control-group
        = label_tag 'representative[circumscription]', 'Circumscripcion', class: 'control-label'
        .controls
          = text_field_tag 'representative[circumscription]'

      .control-group
        = label_tag 'representative[political_party_id]', 'Partido politico', class: 'control-label'
        .controls
          = select_tag 'representative[political_party_id]', options_from_collection_for_select(PoliticalParty.all, :id, :name)

      .control-group
        = label_tag 'representative[email]', 'Email', class: 'control-label'
        .controls
          = text_field_tag 'representative[email]'

      .control-group
        = label_tag 'representative[phone]', 'Telefono', class: 'control-label'
        .controls
          = text_field_tag 'representative[phone]'

      .control-group
        = label_tag 'representative[twitter]', 'Twitter', class: 'control-label'
        .controls
          = text_field_tag 'representative[twitter]'

  .modal-footer
    %a#close-modal.btn{href: "#"} Cerrar
    %a#quick-edition-submit.btn.btn-primary{href: "#"} Guardar cambios
    
- content_for :javascript do
  $('.quick-edition').click(function(event){
  event.preventDefault();
  form = $('#quick-edition-modal form');
  $.getJSON('representatives/' + $(this).data('representative-id') +'.json', function(data){
  form.attr('action','/admin/representatives/' + data.id)
  form.find('#representative_first_name').val(data.first_name);
  form.find('#representative_last_name').val(data.last_name);
  form.find('#representative_district').val(data.district);
  form.find('#representative_circumscription').val(data.circumscription);
  form.find('#representative_email').val(data.email);
  form.find('#representative_phone').val(data.phone);
  form.find('#representative_twitter').val(data.twitter);
  form.find('select option[value=' + data.political_party_id + ']').attr('selected','selected');
  });

  $('#quick-edition-modal').modal();
  });

  $('#quick-edition-modal').on('hide', function() {
  form = $('#quick-edition-modal form');
  form.find('input').val('');
  form.find('option:selected').removeAttr('selected');
  });
  
  $('#close-modal').click(function(event){
  event.preventDefault();
  $('#quick-edition-modal').modal('hide');
  });
  
  $('#quick-edition-submit').click(function(event) {
  event.preventDefault();
  $('#quick-edition-modal form').submit();
  });

app/views/representatives/new.html.haml
.box
  .box-title
    %h2 Nuevo Representante
  .box-content
    = form_for @representative, :html => {:multipart => true, class: 'form-horizontal'} do |form|
      = render "shared/error_messages", :target => @representative
      = render :partial => 'form', :locals => {:form => form}
      .form-actions
        = form.submit 'Crear Representante', :class => 'btn btn-primary'
        %input{:type => 'reset', :class => 'btn', :value => 'Limpiar'}

app/views/representatives/show.html.haml
.box
  .box-title
    %h2= @representative.name

.row-fluid
  .span12
    .box
      .box-title
        Visitas Recientes
      .box-content.nopadding
        #views-chart
        
.row-fluid
  .span6
    .box
      .box-title
        Comentarios Recientes
      .box-content
        %table.table.table-striped.table-bordered.dataTable
          %thead
            %tr
              %th Comentario
              %th Autor
              %th Acciones
          %tbody
            = render partial: 'comment', collection: @comments
        
        #datatable_paginate.dataTables_paginate.paging_full_numbers
          = paginate @comments

  .span6
    .box
      .box-title
        Comentarios Recientes
      .box-content.nopadding
        #comments-chart

- content_for :javascript do
  $('a[rel=popover]').popover({placement: 'bottom'});
  
  var view_plot = $.plot($("#views-chart"),
  [{ data: #{@representative.comments.last_10_days_count.to_s.html_safe}, label: "Vistas", color: "#000000"}], {
  series: {
  lines: { show: true, fill: true, fillColor: { colors: [ { opacity: 0.05 }, { opacity: 0.15 } ] } },
  points: { show: true }
  },
  legend: { position: 'nw'},
  grid: { hoverable: true, clickable: true, borderColor: '#ccc', borderWidth: 1, labelMargin: 10 },
  yaxis: { min: 0, max: 15 },
  xaxis: {
  mode: "time",
  min: (new Date('#{10.day.ago.strftime("%m/%d")}')).getTime(),
  max: (new Date('#{1.day.ago.strftime("%m/%d")}')).getTime(),
  timeformat: "%m/%d"
  }
  });
  
  var plot = $.plot($("#comments-chart"),
  [{ data: #{@representative.comments.last_10_days_count.to_s.html_safe}, label: "Comentarios", color: "#0B689F"}], {
  series: {
  lines: { show: true, fill: true, fillColor: { colors: [ { opacity: 0.05 }, { opacity: 0.15 } ] } },
  points: { show: true }
  },
  legend: { position: 'nw'},
  grid: { hoverable: true, clickable: true, borderColor: '#ccc', borderWidth: 1, labelMargin: 10 },
  yaxis: { min: 0, max: 15 },
  xaxis: {
  mode: "time",
  min: (new Date('#{10.day.ago.strftime("%m/%d")}')).getTime(),
  max: (new Date('#{1.day.ago.strftime("%m/%d")}')).getTime(),
  timeformat: "%m/%d"
  }
  });